Class 19 examples and playground.

In [2]:
import pandas as pd
import numpy as np

In [3]:
array1 = np.array([8,5,3,2,1,1]) #Have to be same data type.
print(array1)

[8 5 3 2 1 1]


In [7]:
arraymd = np.array([[1,1,1],[2,2,2],[3,3,3]])
arraymd2 = np.array([[2,2,2],[3,3,3],[1,1,1]])

In [8]:
arrayx = arraymd2 * arraymd
print(arrayx)

[[2 2 2]
 [6 6 6]
 [3 3 3]]


In [9]:
print(arrayx.ndim) #This is looking at how many coordinates are in the array such as (x,y)

print(arrayx.shape) #Tells numbers of rows and columns

2
(3, 3)


In [11]:
array3d = np.array([[[1,2], [2,3]], [[1,2], [2,3]]])

In [12]:
print(array3d)
print(array3d.ndim)

[[[1 2]
  [2 3]]

 [[1 2]
  [2 3]]]
3


In [16]:
arrayc0 = np.concatenate((arrayx, arraymd), axis = 0)
arrayc1 = np.concatenate((arrayx, arraymd), axis = 1)


print(arrayc0)
print(arrayc1)


[[4 2 2]
 [6 6 6]
 [3 3 3]
 [1 1 1]
 [2 2 2]
 [3 3 3]]
[[4 2 2 1 1 1]
 [6 6 6 2 2 2]
 [3 3 3 3 3 3]]


In [14]:
print(arrayx)
arrayx[0,0] = arrayx[0,0] *2
print(arrayx)

[[2 2 2]
 [6 6 6]
 [3 3 3]]
[[4 2 2]
 [6 6 6]
 [3 3 3]]


In [17]:
print("The mean of arrayx is", np.mean(arrayx))

The mean of arrayx is 3.888888888888889


In [19]:
example_list = pd.Series(['apples','bananas','grapes'])