In [10]:
import numpy as np

In [11]:
# Create a NumPy array from a list
array1 = np.array([8, 5, 3, 2, 1, 1])
print(array1)

[8 5 3 2 1 1]


In [12]:
array10 = np.array([1,2,3,4,5,6])
print(array10)

[1 2 3 4 5 6]


In [14]:
array2 = np.array([[5,1,3],[1,8,7],[3,7,9]])
print(array2)

[[5 1 3]
 [1 8 7]
 [3 7 9]]


In [20]:
print(f"dimension of array2:", array2.ndim)


dimension of array2: 2


In [24]:
print(f"shape of array2: {array2.shape}")

shape of array2: (3, 3)


In [25]:
print(np.sort(array1))

[1 1 2 3 5 8]


In [26]:
newarray1 = np.array_split(array1, 3)
print(newarray1)

[array([8, 5]), array([3, 2]), array([1, 1])]
